spring.application.name=gato
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: todo
    password: todo
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: "change-me-super-secret-256-bit"
    expiryMinutes: 60
  passwordReset:
    tokenTtlMinutes: 30
logging:
  level:
    root: INFO
    com.example: DEBUG
